[package]
edition = "2021"
name = "zkp-testnet2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[features]
cuda = ["snarkvm-algorithms/cuda"]

[[bench]]
harness = false
name = "testnet2_prove"
path = "benches/prove.rs"

[[bench]]
harness = false
name = "testnet2_marlin"
path = "benches/algorithm_marlin.rs"

[dependencies]
futures = {version = "0.3.21"}
rand = {version = "0.8.5"}
rand_chacha = {version = "0.3"}
rayon = {version = "1.5.3"}
tokio = {version = "1.19.2", features = ["full"]}
num_cpus = { version = "1.13.1" } 

[dependencies.snarkvm]
path = "../../snarkVM-testnet2"

[dependencies.snarkvm-algorithms]
path = "../../snarkVM-testnet2/algorithms"

[dependencies.snarkvm-curves]
path = "../../snarkVM-testnet2/curves"

[dependencies.snarkvm-fields]
path = "../../snarkVM-testnet2/fields"

[dependencies.snarkvm-r1cs]
path = "../../snarkVM-testnet2/r1cs"

[dependencies.snarkvm-utilities]
path = "../../snarkVM-testnet2/utilities"

[dependencies.snarkvm-marlin]
path = "../../snarkVM-testnet2/marlin"

[dependencies.snarkvm-polycommit]
path = "../../snarkVM-testnet2/polycommit"

[dev-dependencies]
criterion = {version = "0.3.5"}