[package]
edition = "2021"
name = "zkp-testnet2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[features]
cuda = ["snarkvm-algorithms/cuda"]

[[bench]]
harness = false
name = "testnet2_prove"
path = "benches/prove.rs"

[[bench]]
harness = false
name = "testnet2_marlin"
path = "benches/algorithm_marlin.rs"

[dependencies]
futures = {version = "0.3.21"}
rand = {version = "0.8.5"}
rand_chacha = {version = "0.3"}
rayon = {version = "1.5.3"}
tokio = {version = "1.19.2", features = ["full"]}
num_cpus = { version = "1.13.1" } 
ansi_term = "0.12.1"

[dependencies.snarkvm]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7" # testnet2 最后一次提交6月30日
# rev = "5a681812a" # 6月14日
# rev = "5f8d31956" # # 2月12日 version="0.8.0"

[dependencies.snarkvm-algorithms]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dependencies.snarkvm-curves]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dependencies.snarkvm-fields]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dependencies.snarkvm-r1cs]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dependencies.snarkvm-utilities]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dependencies.snarkvm-marlin]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dependencies.snarkvm-polycommit]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "3887cbbe7"

[dev-dependencies]
criterion = {version = "0.3.5"}