[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snarkvm = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "3887cbbe7" }
rand = { version = "0.8.5" }


[dev-dependencies.rand_chacha]
version = "0.3"